### ISSUE TITLE
v0.1.1 - Wrong Loot Table in "obsidian_pressure_plate.json"

### ISSUE THREAD

**Issue by rxay579** [BoogieMonster1O1/obsidiplates-fabric#2]
Currently reads:
{
  "type": "minecraft:block",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:obsidian_pressure_plate"
        }
      ],
      "conditions": [
        {
          "condition": "minecraft:survives_explosion"
        }
      ]
    }
  ]
}

Should probably be:
{
  "type": "minecraft:block",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "obsidiplates:obsidian_pressure_plate"
        }
      ],
      "conditions": [
        {
          "condition": "minecraft:survives_explosion"
        }
      ]
    }
  ]
}

**Comment by BoogieMonster1O1** [comment]
Thanks for reporting it! I’ll fix this soon.
If you’d like to contribute, you can also send a pull request with the updated loot table.

**Comment by rxay579** [comment]
I haven't quite figured that much out about Git yet or I'd be happy to be more helpful.

*edit*
Hope I did that pull request correctly.

**Comment by BoogieMonster1O1** [comment]
> I haven't quite figured that much out about Git yet or I'd be happy to be more helpful.
> 
> _edit_
> Hope I did that pull request correctly.

Yep, it was done correctly
